https://flask-sqlalchemy.palletsprojects.com/en/2.x/quickstart/#a-minimal-application

Connecting sqlite to mysql using sqlalchemy
https://stackoverflow.com/questions/27766794/switching-from-sqlite-to-mysql-with-flask-sqlalchemy


Handle GET POST resource
https://pythonprogramming.net/flask-get-post-requests-handling-tutorial/


How to autoincrement table value 
https://www.tutorialspoint.com/how-to-add-auto-increment-to-column-in-mysql-database-using-phpmyadmin

Added mysql support
pip install mysqlclient